# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Shortest path model between cities
#' @description Output the connectivity between each city
#' @param M a direct connection situation matrix of size \code{n*2}
#' @return a matrix of size \code{n*n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' R_shortest(data)
#' }
#' @export
Rcpp_shortest <- function(M) {
    .Call('_StatComp22031_Rcpp_shortest', PACKAGE = 'StatComp22031', M)
}

#' @title A binary normal Gibbs sampler using Rcpp
#' @description Generate a binary normal sample with Gibbs
#' @param N the sample size
#' @param mu1 the mean value of one of the sample
#' @param mu2 the mean value of another sample
#' @param sigma1 the variance of one of the sample
#' @param sigma2 the variance of another sample
#' @param rho the sample correlation coefficient
#' @return A binary normal random sample of size \code{N}
#' @examples
#' \dontrun{
#' gibbs_cpp(5000,0,0,1,1,0.9)
#' }
#' @export
gibbs_cpp <- function(N, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22031_gibbs_cpp', PACKAGE = 'StatComp22031', N, mu1, mu2, sigma1, sigma2, rho)
}

